services:
  db:
    image: postgres:18
    restart: always
    env_file:
      - ./config/.env.database
    environment:
      - PROD=${PROD:-false}
    volumes:
      - ./data:/var/lib/postgres/data

  backend:
    build: ./backend
    env_file:
      - ./config/.env.backend
    environment:
      - PROD=${PROD:-false}
    volumes:
      - ./backend:/app
    depends_on:
      - db

  nginx:
    build: ./nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/templates/default.conf:ro
      - ./nginx/default.dev.conf:/etc/nginx/templates/default.dev.conf:ro
      - ./nginx/certs:/etc/letsencrypt
    env_file:
      - ./config/.env.nginx
    environment:
      - PROD=${PROD:-false}
    depends_on:
      - backend
